@ECHO OFF
REM *** This batch file is for use on Microsoft Windows machines ***
REM *** It creates subdirectories which are required for JOOT to run ***
REM
REM *** Thanks to Phil Alverson for pointing out a slight problem ***

IF "%1" == "" GOTO CREATE_HOW

CD %1
MD users
MD users\people
MD users\people\a
MD users\people\b
MD users\people\c
MD users\people\d
MD users\people\e
MD users\people\f
MD users\people\g
MD users\people\h
MD users\people\i
MD users\people\j
MD users\people\k
MD users\people\l
MD users\people\m
MD users\people\n
MD users\people\o
MD users\people\p
MD users\people\q
MD users\people\r
MD users\people\s
MD users\people\t
MD users\people\u
MD users\people\v
MD users\people\w
MD users\people\x
MD users\people\y
MD users\people\z
MD users\record
MD users\record\a
MD users\record\b
MD users\record\c
MD users\record\d
MD users\record\e
MD users\record\f
MD users\record\g
MD users\record\h
MD users\record\i
MD users\record\j
MD users\record\k
MD users\record\l
MD users\record\m
MD users\record\n
MD users\record\o
MD users\record\p
MD users\record\q
MD users\record\r
MD users\record\s
MD users\record\t
MD users\record\u
MD users\record\v
MD users\record\w
MD users\record\x
MD users\record\y
MD users\record\z
MD users\abbrs
MD users\abbrs\a
MD users\abbrs\b
MD users\abbrs\c
MD users\abbrs\d
MD users\abbrs\e
MD users\abbrs\f
MD users\abbrs\g
MD users\abbrs\h
MD users\abbrs\i
MD users\abbrs\j
MD users\abbrs\k
MD users\abbrs\l
MD users\abbrs\m
MD users\abbrs\n
MD users\abbrs\o
MD users\abbrs\p
MD users\abbrs\q
MD users\abbrs\r
MD users\abbrs\s
MD users\abbrs\t
MD users\abbrs\u
MD users\abbrs\v
MD users\abbrs\w
MD users\abbrs\x
MD users\abbrs\y
MD users\abbrs\z
MD users\commands
MD users\commands\a
MD users\commands\b
MD users\commands\c
MD users\commands\d
MD users\commands\e
MD users\commands\f
MD users\commands\g
MD users\commands\h
MD users\commands\i
MD users\commands\j
MD users\commands\k
MD users\commands\l
MD users\commands\m
MD users\commands\n
MD users\commands\o
MD users\commands\p
MD users\commands\q
MD users\commands\r
MD users\commands\s
MD users\commands\t
MD users\commands\u
MD users\commands\v
MD users\commands\w
MD users\commands\x
MD users\commands\y
MD users\commands\z
MD users\data
MD users\data\a
MD users\data\b
MD users\data\c
MD users\data\d
MD users\data\e
MD users\data\f
MD users\data\g
MD users\data\h
MD users\data\i
MD users\data\j
MD users\data\k
MD users\data\l
MD users\data\m
MD users\data\n
MD users\data\o
MD users\data\p
MD users\data\q
MD users\data\r
MD users\data\s
MD users\data\t
MD users\data\u
MD users\data\v
MD users\data\w
MD users\data\x
MD users\data\y
MD users\data\z
MD users\macros
MD users\macros\a
MD users\macros\b
MD users\macros\c
MD users\macros\d
MD users\macros\e
MD users\macros\f
MD users\macros\g
MD users\macros\h
MD users\macros\i
MD users\macros\j
MD users\macros\k
MD users\macros\l
MD users\macros\m
MD users\macros\n
MD users\macros\o
MD users\macros\p
MD users\macros\q
MD users\macros\r
MD users\macros\s
MD users\macros\t
MD users\macros\u
MD users\macros\v
MD users\macros\w
MD users\macros\x
MD users\macros\y
MD users\macros\z
MD users\profile
MD users\profile\a
MD users\profile\b
MD users\profile\c
MD users\profile\d
MD users\profile\e
MD users\profile\f
MD users\profile\g
MD users\profile\h
MD users\profile\i
MD users\profile\j
MD users\profile\k
MD users\profile\l
MD users\profile\m
MD users\profile\n
MD users\profile\o
MD users\profile\p
MD users\profile\q
MD users\profile\r
MD users\profile\s
MD users\profile\t
MD users\profile\u
MD users\profile\v
MD users\profile\w
MD users\profile\x
MD users\profile\y
MD users\profile\z
MD users\smail
MD users\smail\a
MD users\smail\b
MD users\smail\c
MD users\smail\d
MD users\smail\e
MD users\smail\f
MD users\smail\g
MD users\smail\h
MD users\smail\i
MD users\smail\j
MD users\smail\k
MD users\smail\l
MD users\smail\m
MD users\smail\n
MD users\smail\o
MD users\smail\p
MD users\smail\q
MD users\smail\r
MD users\smail\s
MD users\smail\t
MD users\smail\u
MD users\smail\v
MD users\smail\w
MD users\smail\x
MD users\smail\y
MD users\smail\z
MD users\sent
MD users\sent\a
MD users\sent\b
MD users\sent\c
MD users\sent\d
MD users\sent\e
MD users\sent\f
MD users\sent\g
MD users\sent\h
MD users\sent\i
MD users\sent\j
MD users\sent\k
MD users\sent\l
MD users\sent\m
MD users\sent\n
MD users\sent\o
MD users\sent\p
MD users\sent\q
MD users\sent\r
MD users\sent\s
MD users\sent\t
MD users\sent\u
MD users\sent\v
MD users\sent\w
MD users\sent\x
MD users\sent\y
MD users\sent\z
ECHO Done.

GOTO THE_END

:CREATE_HOW
ECHO.
ECHO Usage: create [dir]
ECHO Where: [dir] specifies the full directory to where
ECHO        your talker data files are located.
ECHO.
ECHO Example: create c:\Joot1-7\nowhere
ECHO.

:THE_END

